name: SteamRIP Scraper
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install puppeteer-extra puppeteer-extra-plugin-stealth axios puppeteer
      - run: npx puppeteer browsers install chrome
      - name: Run Scraper
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: node scraper.js
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lastGames.json
          git commit -m "Update game list" || exit 0
          git push
